// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "CodeStudio Child Project",
    "version": "1"
  },
  "paths": {
    "/sample-post-request": {
      "post": {
        "summary": "sampleLambda",
        "description": "",
        "operationId": "sampleLambda.post.sample-post-request",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/TestRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/sample-get-request": {
      "get": {
        "summary": "checkStatusLambda",
        "description": "",
        "operationId": "checkStatusLambda.get.sample-get-request",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "accesstoken": [],
            "x-api-key": [],
            "Content-Type": []
          }
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "TestRequest": {
      "properties": {
        "name": {
          "title": "TestRequest.name",
          "type": "string"
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false,
      "title": "TestRequest",
      "type": "object"
    },
    "TestResponse": {
      "properties": {
        "name": {
          "title": "TestResponse.name",
          "type": "string"
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false,
      "title": "TestResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {
    "accesstoken": {
      "type": "apiKey",
      "name": "accesstoken",
      "in": "header"
    },
    "x-api-key": {
      "type": "apiKey",
      "name": "x-api-key",
      "in": "header"
    },
    "Content-Type": {
      "type": "apiKey",
      "name": "Content-Type",
      "in": "header"
    }
  },
  "basePath": "/local",
  "host": "localhost:3000",
  "schemes": [
    "http",
    "https"
  ]
};